// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attribute struct {
	Label   string    `json:"label"`
	Options []*Option `json:"options"`
}

type CreateSessionInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Option struct {
	Label string `json:"label"`
	Extra int    `json:"extra"`
}

type Restaurant struct {
	Owner       *User   `json:"owner,omitempty"`
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Items       []*Item `json:"items"`
}

type Session struct {
	Token *string `json:"token,omitempty"`
}

type Table struct {
	ID         string      `json:"id"`
	Label      string      `json:"label"`
	Restaurant *Restaurant `json:"restaurant"`
}

type User struct {
	ID    string  `json:"id"`
	Email *string `json:"email,omitempty"`
	Name  string  `json:"name"`
}
